# Generated by Django 4.0.3 on 2022-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('reference', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('exchange', models.BooleanField()),
                ('donation', models.BooleanField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('categogies', models.ManyToManyField(to='givntek.category')),
            ],
        ),
    ]
