# Generated by Django 4.0.3 on 2022-03-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givntek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categogies',
            new_name='categories',
        ),
    ]
